/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: "https://getsmoke.com",
  // siteUrl: "http://localhost:3000/",
  generateRobotsTxt: true,
  exclude: [
    "/api/*",
    "/admin",
    "/admin/*",
    "/my-account",
    "/my-account/*",
    "/cart",
    "/cart/*",
    "/checkout",
    "/checkout/*",
    "/email-preview",
    "/email-preview/*",
    "/login",
    "/login/*",
    "/signup",
    "/signup/*",
    "/reset-password",
    "/reset-password/*",
    "/forgot-password",
    "/forgot-password/*",
    "/_next/*",
    "/robots.txt",
    "/in-progress",
    "/juicy-bar-jb25000",
    "/juicy-bar-jb5000",
    "/juicy-bar-jb7500",
    "/adults-goods",
    "/supplements",
  ],
  generateIndexSitemap: true,
  sitemapSize: 7000,

  // Static pages
  additionalPaths: async (config) => {
    const result = [];

    // Add your static pages here
    const staticPages = [
      { loc: "/", priority: 1.0, changefreq: "daily" },
      { loc: "/about", priority: 0.8, changefreq: "monthly" },
      { loc: "/contact", priority: 0.8, changefreq: "monthly" },
      { loc: "/privacy-policy", priority: 0.5, changefreq: "yearly" },
      { loc: "/return-policy", priority: 0.5, changefreq: "yearly" },
      { loc: "/shipping-policy", priority: 0.5, changefreq: "yearly" },
      { loc: "/terms-conditions", priority: 0.5, changefreq: "yearly" },
      { loc: "/blog", priority: 0.5, changefreq: "daily" },
      { loc: "/accessories", priority: 0.5, changefreq: "daily" },
      { loc: "/hookah", priority: 0.5, changefreq: "daily" },
      { loc: "/vapes", priority: 0.5, changefreq: "daily" },
      // Collection pages (nicotine / puffs / flavor)
      { loc: "/5-percent-nicotine-vapes", priority: 0.8, changefreq: "weekly" },
      { loc: "/nicotine-free-vapes", priority: 0.8, changefreq: "weekly" },
      { loc: "/20000-puff-vapes", priority: 0.8, changefreq: "weekly" },
      { loc: "/25000-puff-vapes", priority: 0.8, changefreq: "weekly" },
      { loc: "/coffee-flavored-disposable-vapes", priority: 0.8, changefreq: "weekly" },
      { loc: "/new-in-stock", priority: 0.7, changefreq: "daily" },
      // Definition / AI answer pages
      { loc: "/what-is-a-disposable-vape", priority: 0.8, changefreq: "monthly" },
      { loc: "/what-is-nicotine-salt", priority: 0.8, changefreq: "monthly" },
      // How-To pages
      { loc: "/how-to-use-geek-bar-pulse-x", priority: 0.8, changefreq: "monthly" },
      { loc: "/how-to-charge-raz-vape", priority: 0.8, changefreq: "monthly" },
      { loc: "/how-to-use-lost-mary-mt35000-turbo", priority: 0.8, changefreq: "monthly" },
      { loc: "/how-to-use-hqd-cuvie", priority: 0.8, changefreq: "monthly" },
      // City delivery pages
      { loc: "/vape-delivery-boston-massachusetts", priority: 0.7, changefreq: "monthly" },

      // Model pages (49 models - must be listed here to survive next-sitemap rebuild)
      { loc: "/models/adjust-mycool-40000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/adjust-myflavor-40000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/adjust-mysour-40000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/adjust-mysweet-40000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/beri-crush-50000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/ebcreate-bc-pro-40000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/fifty-bar-black-series-20000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/fruitia-fifty-bar-20000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/fifty-bar-hidden-hills-20000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/foger-bit-35000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/foger-switch-pro-30000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/foger-switch-pro-pod-30000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/fume-extra-1500-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/fume-hookah-20000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/fume-infinity-4500-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/fume-nb-super-k-20000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/fume-pro-30000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/fume-recharge-zero-5000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/geek-bar-skyview-30000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/geek-bar-meloso-30000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/geek-bar-meloso-mini-1500-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/geek-bar-pulse-x-25000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/geek-bar-pulse-15000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/geek-bar-pulse-x2-25000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/geek-bar-pulse-2-25000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/hqd-cuvie-bar-7000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/hqd-cuvie-glaze-15000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/hqd-cuvie-mars-8000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/hqd-cuvie-plus-1200-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/hqd-cuvie-slick-6000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/hqd-everest-25000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/hqd-shisha-20000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/juice-bar-jb5000-5000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/juice-bar-jb7500-7500-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/juice-bar-jb25000-25000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/lost-mary-mo20000-20000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/lost-mary-nera-fullview-70000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/lost-mary-nera-pureview-40000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/lost-mary-turbo-35000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/lost-mary-ultrasonic-35000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/oxbar-astro-maze-50000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/oxbar-ice-nic-35000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/oxbar-ice-nic-pod-juice-35000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/raz-dc25000-25000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/raz-dc25000-zero-25000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/raz-tn9000-9000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/raz-vue-50k-50000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/viho-supercharge-20000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/viho-supercharge-pro-20000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/viho-supercharge-zero-20000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/x-posed-35k-35000-puffs", priority: 0.8, changefreq: "weekly" },
      { loc: "/models/x-posed-pod-35k-35000-puffs", priority: 0.8, changefreq: "weekly" },
    ];

    staticPages.forEach((page) => {
      result.push({
        loc: page.loc,
        changefreq: page.changefreq,
        priority: page.priority,
        lastmod: new Date().toISOString(),
      });
    });

    return result;
  },

  robotsTxtOptions: {
    policies: [
      {
        userAgent: "*",
        allow: "/",
      },
      {
        userAgent: "*",
        disallow: [
          "/admin/*",
          "/api/*",
          "/dashboard/*",
          "/_next/*",
          "/my-account/*",
          "/cart/*",
          "/checkout/*",
          "/email-preview/*",
          "/login/*",
          "/signup/*",
          "/reset-password/*",
          "/forgot-password/*",
        ],
      },
    ],
    additionalSitemaps: [
      "https://getsmoke.com/server-sitemap-products.xml",
      "https://getsmoke.com/server-sitemap-blog.xml",
    ],
  },
};
